### PR TITLE
Minor changes set

### PR DESCRIPTION
**Pull request by lynnporu**
This PR includes some unclassified additions and fixings:
* Fix using old functions in `HumanTrainer`.
* Add language-specific properties to `utdxposdata.json`.
* Prevent parsing empty tokens in `ConlluReader`.
* Add new objects to config: `fp`, `jsonfp`, `lambda`, `defined`, fix object addressing.
* Refactor all the scripts using `Predefinator`.
* Refactor all the classes in accordance with changes in scripts.
* Small fixings.

### CODE REVIEW

**Comment by lynnporu** [comment]
This pull request **fixes 1 alert** when merging c4de7c120e1a32f03ecb9645bbfdc5b931205546 into 15cf952f9ef1c8c98fdcedb3b91eb0717078ac97 - [view on LGTM.com](https://lgtm.com/projects/g/syntpump/syntext-py-ua/rev/pr-7bc2e6ff15dc7345a45b90086ed172f933b57985)

**fixed alerts:**

* 1 for Non\-exception in &#39;except&#39; clause

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by mrtoadstooler** [comment]
Wow! Great job.

**Comment by lynnporu** [comment]
This pull request **fixes 1 alert** when merging 8a34f362a79be9f32833f814e13ee011401062d1 into 15cf952f9ef1c8c98fdcedb3b91eb0717078ac97 - [view on LGTM.com](https://lgtm.com/projects/g/syntpump/syntext-py-ua/rev/pr-09b20bd66cbbaec40dc89b69d8977a0df09b717d)

**fixed alerts:**

* 1 for Non\-exception in &#39;except&#39; clause

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by iasx** [comment]
Wow, great job!

**Review by iasx — APPROVED** [review]
Actually, it's pretty nice

**Pull request merged**
